### your site title here

title: Daas Design
baseurl: /daasdesign # name of the repository
email: ruben@daasdesign.nl

highlighter: rouge
markdown: kramdown
### exclude the instructions / write-up in the README.md
# Collections
collections:
- work

# Tracker
# analytics: UA-83979019-1

# Comments
# disqus-shortname: webjeda-demo

sass:
 style: compressed

exclude:
- README.md


gems: [jekyll-seo-tag, jekyll-paginate]
